# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test_bcp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test_bcp

  target 'test_bcpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'test_bcpUITests' do
    # Pods for testing
  end

end
